title: "Project Docs"
email: "analaura.francisco@gmail.com"
description: "Os melhores tutoriais detalhados em um só lugar!"
baseurl: "" # the subpath of your site, e.g. "/repo"
url: "https://docprojects.github.io" # replace USERNAME
twitter_username: "USERNAME"
github_username: "analaurafra"

# theme: jekyll-theme-minimal
#theme: "jekyll-theme-leap-day"
remote_theme: pages-themes/leap-day@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/page:num/"

exclude:
  - "node_modules"
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

safe: true
keep_files: ["assets"]

include:
  - ".well-known"


